sudo: false

cache:
  pip: true

language: python
python:
  - "3.5"

install:
  - pip install -U pip
  - travis_wait pip install --no-deps -r requirements.txt

script:
  - py.test --cov-config=.coveragerc --cov=contextgraph contextgraph

services:
  - redis-server
