redis:
  container_name: miracle_redis
  expose:
    - "6379"
  image: redis:2.8
  ports:
    - "6379"


kinesis:
  container_name: miracle_kinesis
  expose:
    - "4567"
  build: ./docker/kinesis
  ports:
    - "4567"

s3:
  container_name: miracle_s3
  command: server /export
  environment:
    MINIO_ACCESS_KEY: "access"
    MINIO_SECRET_KEY: "password"
  expose:
    - "9000"
  image: minio/minio
  ports:
    - "9000:9000"
