dynamodb:
  container_name: miracle_dynamodb
  expose:
    - "8000"
  build: ./docker/dynamodb
  ports:
    - "8000:8000"

redis:
  container_name: miracle_redis
  expose:
    - "6379"
  image: redis:2.8
  ports:
    - "6379"

s3:
  container_name: miracle_s3
  command: server /export
  environment:
    MINIO_ACCESS_KEY: "access"
    MINIO_SECRET_KEY: "password"
  expose:
    - "9000"
  image: minio/minio
  ports:
    - "9000:9000"
