dynamodb:
  container_name: miracle_dynamodb
  expose:
    - "8000"
  build: ./docker/dynamodb
  ports:
    - "8000"
  dns:
    - "127.0.0.1"


kinesis:
  container_name: miracle_kinesis
  expose:
    - "4567"
  build: ./docker/kinesis
  ports:
    - "4567"
  dns:
    - "127.0.0.1"


s3:
  container_name: miracle_s3
  command: server /export
  environment:
    MINIO_ACCESS_KEY: "access"
    MINIO_SECRET_KEY: "password"
  expose:
    - "9000"
  image: minio/minio
  ports:
    - "9000:9000"
  dns:
    - "127.0.0.1"
